nodes = [
  { :hostname => 'vault',     :ip => '10.130.50.2'  },
  { :hostname => 'cmp',       :ip => '10.130.50.3'  },
  { :hostname => 'pvwa',      :ip => '10.130.50.10' },
  { :hostname => 'trusty',    :ip => '10.130.50.75' },
  { :hostname => 'centos7',   :ip => '10.130.50.76' },
  { :hostname => 'solaris11', :ip => '10.130.50.77' },
  { :hostname => 'win10',     :ip => '10.130.50.80' },
  { :hostname => 'win2016',   :ip => '10.130.50.81' },
  { :hostname => 'dns',       :ip => '8.8.8.8'      }
]

Vagrant.configure("2") do |config|

#############
### VAULT ###
#############

  config.vm.define "vault" do |cfg|
    cfg.vm.url "file:///~/CyberArk/private_software/boxes/cyberark_vault.box"
    cfg.vm.hostname = "vault"
    cfg.vm.gui = false
    cfg.vm.boot_timeout = 600
    cfg.winrm.transport = :plaintext
    cfg.vm.communicator = "winrm"
    cfg.vm.network :public_network, ip: nodes[:vault], dns: nodes[:dns]

    cfg.vm.provision "shell", inline: 'cscript c:\windows\system32\slmgr.vbs /dlv', privileged: false

    cfg.vm.provider "virtualbox" do |vb, override|
      vb.gui = true
      vb.name = "vault"
      vb.default_nic_type = "82545EM"
      vb.customize ["modifyvm", :id, "--memory", 1536]
      vb.customize ["modifyvm", :id, "--cpus", 1]
      vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
  end
end